version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    volumes:
      - qdrant_storage:/qdrant/storage
    ports: ["6333:6333"]

  rag:
    build: .
    depends_on: [qdrant]
    environment:
      QDRANT_URL: http://qdrant:6333
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GEN_MODEL: TheBloke/Llama-2-13B-chat-GPTQ

    ports: ["8000:8000"]



volumes:
  qdrant_storage: